### ISSUE TITLE
Can't see input box because of auto-scrolling

### ISSUE THREAD

**Issue by eoinnoble** [UCDavisLibrary/scribeAPI#1]
It looks like there's code that runs on every keystroke in the input field that tries to scroll the browser window so that the part of the image to be transcribed is in the centre of the screen. Mostly this is fine, but for especially large image areas this means that the input box can be pushed off the screen, making it impossible to see what you're typing.

**Comment by eoinnoble** [comment]
Here's an example of one, the image of the monk-like character: https://labelthis.lib.ucdavis.edu/view/4388

**Comment by lizadaly** [comment]
Fixed and deployed.
