### ISSUE TITLE
Share buttons don't update

### ISSUE THREAD

**Issue by eoinnoble** [UCDavisLibrary/scribeAPI#3]
The share buttons point to the first label that you transcribed, and don't update to reflect the one that you're currently transcribing. This can make it difficult to share problematic labels!

**Comment by lizadaly** [comment]
@eoinnoble I can't reproduce this (anymore). Is this still happening for you? (Note that I intend to make sharing much easier with #8)

**Comment by lizadaly** [comment]
Couldn't reproduce this.

**Comment by lizadaly** [comment]
This turned out to be a duplicate of #18
