### ISSUE TITLE
Transcription target hidden under footer

### ISSUE THREAD

**Issue by eoinnoble** [UCDavisLibrary/scribeAPI#4]
Every so often the transcription box appears in the footer and nothing is highlighted in the label image above. This recently happened with what looks to be a very large label (screenshot attached), which makes me think that the transcription target may be hidden beneath the footer somehow.

<img width="1330" alt="screen shot 2016-07-08 at 12 26 53" src="https://cloud.githubusercontent.com/assets/3576438/16686102/ab1b32be-4507-11e6-9398-784e5eac0cbd.png">

**Comment by lizadaly** [comment]
I think you're right about the diagnosis. We're tracking a separate bug where the viewport doesn't resize fully when the label changes. #7

**Comment by lizadaly** [comment]
Fixed and deployed: 

![screen shot 2016-07-11 at 2 15 15 pm](https://cloud.githubusercontent.com/assets/19571/16741583/f7261784-4771-11e6-981a-9194aa1fa5c9.png)
